version: 0.2

env:
  variables:
    ECR_ID: 645095421007.dkr.ecr.us-east-1.amazonaws.com
    REPOSITORY_URL: 645095421007.dkr.ecr.us-east-1.amazonaws.com/laravel_rds
    TASK_DEFINITION_NAME: Taskdef-laravel-rds
    CLUSTER_NAME: laravel-rds
    SERVICE_NAME: ser-Laravel-ECR-ECS
    AWS_ACCOUNT_ID: 645095421007
    AWS_DEFAULT_REGION: us-east-1
    ECR_REPOSITORY: laravel_rds
    

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get update && apt-get install -y docker
      - pip3 install awscli
      - cp ./my-laravel-app/.env.example ./my-laravel-app/.env
      
  pre_build:
    commands:
      - echo Running pre-build steps...
      - echo Hello-0
      - echo $AWS_DEFAULT_REGION
      - echo $ECR_ID
      - aws ecr get-login-password --region "${AWS_DEFAULT_REGION}" | docker login --username AWS --password-stdin "${ECR_ID}"
      - echo Hello-1
      - echo "Pulling latest image"
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:latest || true
      - echo Hello-2
  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t $ECR_REPOSITORY .
      - docker tag $ECR_REPOSITORY:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:latest
      - echo Hello-4

      
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:latest
      - echo "Updating ECS service"
      - echo Hello-5
      - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
      - echo Hello-6


