version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - apt-get update
      - apt-get install -y amazon-ecr-credential-helper

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      
  build:
    commands:
      - echo "Building the Docker image"
     
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR"
   
