version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get update && apt-get install -y docker
      
  pre_build:
    commands:
      - echo Running pre-build steps...
      - echo Hello-0
  
  build:
    commands:
      - echo Building the application...
      - echo Hello-1
      
  post_build:
    commands:
      - echo Running post-build steps...
      
      - echo Build and tests complete.

      - echo Hello-2

artifacts:
  files:
    - '**/*'                # Include all files as artifacts
  discard-paths: yes         # Discard directory structure when uploading to S3
  #base-directory: build/      # Specify the base directory where the build output is located
