version: 0.2

variables:
  ECR_ID: 645095421007.dkr.ecr.us-east-1.amazonaws.com
  REPOSITORY_URL: 645095421007.dkr.ecr.us-east-1.amazonaws.com/laravel_rds
  TASK_DEFINITION_NAME: Taskdef-laravel-rds
  CLUSTER_NAME: laravel-rds
  SERVICE_NAME: ser-Laravel-ECR-ECS

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get update && apt-get install -y docker
      - pip3 install awscli
      
  pre_build:
    commands:
      - echo Running pre-build steps...
      - echo Hello-0
      - aws ecr get-login-password --region "${AWS_DEFAULT_REGION}" | docker login --username AWS --password-stdin "${ECR_ID}"
      - echo Hello-1
      - docker build -t laravel_rds .
      - echo Hello-2
      - docker tag laravel_rds:latest 645095421007.dkr.ecr.us-east-1.amazonaws.com/laravel_rds:latest
      - echo Hello-3
      - docker push $REPOSITORY_URL:latest
      - echo Hello-4
  
  build:
    commands:
      - echo Building the application...
      - echo Hello-1
      
  post_build:
    commands:
      - echo Running post-build steps...
      
      - echo Build and tests complete.

      - echo Hello-2


