version: 0.2

variables:
  ECR_ID: 645095421007.dkr.ecr.us-east-1.amazonaws.com
  REPOSITORY_URL: 645095421007.dkr.ecr.us-east-1.amazonaws.com/laravel_rds
  TASK_DEFINITION_NAME: Taskdef-laravel-rds
  CLUSTER_NAME: laravel-rds
  SERVICE_NAME: ser-Laravel-ECR-ECS

phases:
  install:
    commands:
      - echo Installing dependencies...
      
  pre_build:
    commands:
      - echo Running pre-build steps...
      - echo Hello-0
  
  build:
    commands:
      - echo Building the application...
      - echo Hello-1
      
  post_build:
    commands:
      - echo Running post-build steps...
      
      - echo Build and tests complete.

      - echo Hello-2

artifacts:
  files:
    - '**/*'                # Include all files as artifacts
  discard-paths: yes         # Discard directory structure when uploading to S3
  base-directory: build/      # Specify the base directory where the build output is located
